## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## allow failures (tests will run but not make your overall status red)
matrix:
 fast_finish: true
 allow_failures:
   - julia: nightly
     env: TEST_SUITE='using Pkg; Pkg.develop("TaylorModels"); Pkg.clone(pwd()); Pkg.build("Reachability"); Pkg.test("Reachability"; coverage=true)'
 include:
   - julia: 1.0
     env: TEST_SUITE='using Pkg; Pkg.develop("TaylorModels"); Pkg.clone(pwd()); Pkg.build("Reachability"); Pkg.test("Reachability"; coverage=true)'
   - julia: 1.0
     env: TEST_SUITE='using Pkg; Pkg.develop("LazySets"); Pkg.develop("MathematicalSystems"); Pkg.develop("HybridSystems"); Pkg.develop("TaylorModels"); Pkg.clone(pwd()); Pkg.build("Reachability"); Pkg.test("Reachability"; coverage=true)'

## uncomment the following lines to override the default test script
script:
 - julia -e "$TEST_SUITE"

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter");
              Pkg.pin(PackageSpec(name="Documenter", version="0.19.7"));'
  - julia -e 'using Pkg; cd(Pkg.dir("Reachability")); include(joinpath("docs", "make.jl"))'
  # code coverage (for both Coveralls and Codecov)
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  # push coverage results to Coveralls
  #- julia -e 'using Pkg; cd(Pkg.dir("Reachability")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Reachability")); using Coverage; Codecov.submit(Codecov.process_folder())'
